# Generated by Django 4.0 on 2021-12-17 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='constituer',
            name='nom_produit',
        ),
    ]
