# Generated by Django 4.0 on 2021-12-27 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0002_remove_constituer_nom_produit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constituer',
            name='qte_produit',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
