# Generated by Django 4.0 on 2022-01-07 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0003_alter_constituer_qte_produit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='livraison',
        ),
    ]
