# Generated by Django 4.0 on 2022-01-07 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0004_remove_commande_livraison'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='date_commande',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='commande',
            name='date_reglement',
            field=models.DateTimeField(null=True),
        ),
    ]
