# Generated by Django 4.0 on 2022-01-08 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0005_alter_commande_date_commande_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='transaction_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
