# Generated by Django 4.0 on 2022-02-15 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0006_commande_transaction_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='date_commande',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='date_reglement',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='mode_paiement',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='total_commande',
        ),
        migrations.AddField(
            model_name='commande',
            name='date_creation',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
