# Generated by Django 4.0 on 2021-12-11 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categorie', '0001_initial'),
        ('vendeur', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, null=True)),
                ('description', models.CharField(max_length=200, null=True)),
                ('prix_achat', models.FloatField()),
                ('remise', models.FloatField()),
                ('prix_livraison', models.FloatField()),
                ('marque', models.CharField(max_length=200, null=True)),
                ('image', models.FileField(upload_to='')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categorie.categorie')),
                ('vendeurs', models.ManyToManyField(to='vendeur.Vendeur')),
            ],
        ),
    ]
