# Generated by Django 4.0 on 2022-03-30 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0005_remove_produit_remise_produit_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produit',
            old_name='Stock',
            new_name='stock',
        ),
    ]
