# Generated by Django 4.0 on 2022-03-30 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0006_rename_stock_produit_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='prix_achat',
            field=models.FloatField(default=0),
        ),
    ]
