# Generated by Django 4.0 on 2022-03-30 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0007_alter_produit_prix_achat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='prix_achat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='produit',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
