# Generated by Django 4.0.4 on 2022-04-29 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendeur', '0001_initial'),
        ('produit', '0008_alter_produit_prix_achat_alter_produit_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='vendeurs',
        ),
        migrations.AddField(
            model_name='produit',
            name='vendeurs',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vendeur.vendeur'),
            preserve_default=False,
        ),
    ]
