# Generated by Django 4.0 on 2021-12-31 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livraison', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livraison',
            name='prix_livraison',
            field=models.FloatField(null=True),
        ),
    ]
