# Generated by Django 4.0 on 2022-01-28 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livraison', '0012_alter_livraison_commande'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livraison',
            name='prix_livraison',
        ),
        migrations.AddField(
            model_name='livraison',
            name='date_creation',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='livraison',
            name='numero',
            field=models.IntegerField(null=True),
        ),
    ]
