# Generated by Django 4.0 on 2022-02-01 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livraison', '0013_remove_livraison_prix_livraison_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livraison',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
