# Generated by Django 4.0 on 2022-03-01 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
        ('livraison', '0014_livraison_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livraison',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='livraison',
            name='email',
        ),
        migrations.RemoveField(
            model_name='livraison',
            name='nom_destinataire',
        ),
        migrations.RemoveField(
            model_name='livraison',
            name='numero',
        ),
        migrations.RemoveField(
            model_name='livraison',
            name='prenom_destinataire',
        ),
        migrations.AddField(
            model_name='livraison',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='client.client'),
            preserve_default=False,
        ),
    ]
