# Generated by Django 4.0 on 2022-03-01 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livraison', '0015_remove_livraison_destination_remove_livraison_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livraison',
            name='client',
        ),
    ]
